### ISSUE TITLE
Default to HTTPS

### ISSUE THREAD

**Issue by bhubbard** [olivierlacan/keep-a-changelog#105]
http://keepachangelog.com should be updated and default to HTTPS. This can easily be accomplished with a service such as CloudFlare or Let's Encrypt.

**Comment by olivierlacan** [comment]
Sadly can’t do Let’s Encrypt while we’re hosted on GitHub (for free) and I don’t want to do CloudFlare because they block all Tor traffic by default. So for now we’ll stay on HTTP until perhaps GitHub offers a solution for SSL.


On April 17, 2016 at 9:31:36 PM, Brandon Hubbard (notifications@github.com) wrote:

http://keepachangelog.com should be updated and default to HTTPS. This can easily be accomplished with a service such as CloudFlare or Let's Encrypt.

**Comment by olivierlacan** [comment]
No plans to do that currently since I'd rather not spend money on hosting at this point. Sorry.

**Comment by bhubbard** [comment]
@olivierlacan I understand the hosting cost, although I should note you may want to reconsider CloudFlare as you can now choose to whitelist Tor traffic. 

https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-
