### ISSUE TITLE
Discuss whether to keep old changelogs?

### ISSUE THREAD

**Issue by Blaisorblade** [olivierlacan/keep-a-changelog#122]
I obviously do, but apparently people have different ideas, especially for apps. (Single example: https://github.com/farkam135/GoIV/pull/186).

**Comment by olivierlacan** [comment]
@Blaisorblade Can you give more details regarding the context for this? 

Do you mean situation in which changelogs for very old versions is separated in a different file. I think we've discussed this in the past and my position is quite simple. A single changelog file is much better, even across concurrently maintained branches (e.g. Rails' `4-2-stable` and `3-2-stable` branches where it's tricky to keep track of things that are backported) because it doesn't put the onus on the end-user to hunt for the right branch.

In my mind, any version released prior to the current state of the changelog (in terms of git commits) should be documented in `CHANGELOG.md`. And since it's an extremely lightweight text file, it should contain changes for every possible version as far back as the very first one.

**Comment by Blaisorblade** [comment]
I agree with you—which is why it'd be good to have it your position (or reasonable ones) on the website.

In that context, people wanted to remove old changelogs altogether, leaving them in the repo history (or, as proposed, even the repo history of a Git wiki, which is like the most hidden thing ever). The only motivation I got was a concern for "bloat" in the repo 😰 . Which is why I looked for some authoritative argument on changelogs, to avoid debating it.
