### ISSUE TITLE
Add section `Chore` in version

### ISSUE THREAD

**Issue by evilebottnawi** [olivierlacan/keep-a-changelog#134]
Sometimes it occurs in the project work that we would like to monitor. For example treatment of duplicate testing and cleanup.

**Comment by roalz** [comment]
@evilebottnawi Can you elaborate, it's not clear (at least to me) what you are talking about. Thank you

**Comment by evilebottnawi** [comment]
@roalz 
```md
## [Unreleased]
### Added
- zh-CN and zh-TW translations from @tianshuo.
- de translation from @mpbzh.
- it-IT translation from @roalz.
- sv translation from @magol.
- tr-TR translation from @karalamalar.
- fr translation from @zapashcanon.

### Changed
- Start versioning based on the current English version at 0.3.0 to help
translation authors keep things up-to-date.
- Fix typos in zh-CN translation.
- Fix typos in pt-BR translation.

### Chore
- Use spaces instead tab in indentation.
```

**Comment by das-g** [comment]
What would be the meaning of this? Would that section be about maintenance changes that have been done in the respective (maybe yet unreleased) release (i.e. in your example: "We've replaced tabs used for indentation with spaces") or are they about stuff to be remembered (kinda an orthorgonal, cross-cutting TODO, i.e. for your example "When making any change, please remember to indent the changed or added code with spaces instead of tabs")?

If the former, why not just list it under section "Changed"?
If the latter, wouldn't a separate `CONTRIBUTING.md` be a better place for such notes?

**Comment by evilebottnawi** [comment]
@das-g `Changed` major release (breaking changed), `Added` minor release, chore is just chore

**Comment by das-g** [comment]
So that means this would be about chores that _have been done_ in the respective release, not a reminder of chores to do?

**Comment by evilebottnawi** [comment]
@das-g yep

**Comment by olivierlacan** [comment]
Doesn't make sense to me.
