### ISSUE TITLE
[RFC] adding a "Breaking Changes" change type

### ISSUE THREAD

**Issue by majormoses** [olivierlacan/keep-a-changelog#200]
I am a maintainer for 180+ sensu plugins and extensions and we use this as a great base, we found that users really liked calling out breaking changes more obviously as it allowed them very quickly evaluate and determine an upgrade path.

Most of the time the most important questions to be asked are:
1. is there a breaking change? Does it affect me?
1. is there a new feature/fix I could use that requires no effort other than pulling in the new version?

Anyways just wondering if it makes sense to attempt to get something like this into wider practice or if we should just create our flavor on top like we started doing. Here is an example of how we started doing it: https://github.com/sensu-plugins/sensu-plugins-aws/blob/8.0.0/CHANGELOG.md and our community has responded very positively to this.

**Comment by gilmrjc** [comment]
There is a discussion here about it #41. I feel breaking changes should not have it's own section because they are changes, and already have their a section. I prefer to use markdown like `**BREAKING**:` to separate breaking vs non-breaking changes because you can see clearly what you're looking for: 

### Changed

- **BREAKING**: Arguments of the method abc()  now are required instead of optional.
- Method xyz() accepts a new optional parameter `sorted` which defaults to false to preserve behavior.

Also, if you use SemVer, any added feature is non-breaking and any removal should be expected to be breaking. In the latter case you should deprecate things before changing or removing them. This is more helpful to developers than a simple BREAKING statement.

**Comment by majormoses** [comment]
I must have missed that, I will re-post there and close this out to avoid multiple streams.
