### ISSUE TITLE
Add accessibility section

### ISSUE THREAD

**Issue by SamWhited** [olivierlacan/keep-a-changelog#258]
Along with the current types of changes (added, changed, deprecated, removed, fixed, and security) I would like to recommend a section for accessibility.
Like "security" this would let someone concerned with accessibility see at a glance if, for example, their screenreader will work with the newest version without having to decide if that was an addition or a change, or a bug fix to a widget, etc.

**Comment by olivierlacan** [comment]
I would consider that either an addition, a change, or a fix, depending on the case. I'm afraid that'd be getting a bit too specific but again, categories that recur are fine as long as you think you'll regularly have them included in releases.

If you can think of only a few releases that would include it, you're probably making these categories too specific and they will make things harder to find rather than easier.
