### ISSUE TITLE
Version mismatches on keepachangelog.com

### ISSUE THREAD

**Issue by coproc** [olivierlacan/keep-a-changelog#320]
* Changelog of keepachangelog.com displayed on web page (directly below version info 'Version 1.1.0') is from version 1.0.0
* Drow-down-list on top right of web page only offers translations of version 1.0.0. But when selecting '1.0.0 English' the version info 'Version 1.1.0' is displayed.

**Comment by olivierlacan** [comment]
Good catch! The hiccup here it twofold:
1. we're loading the `CHANGELOG.md` [with Ruby][1] at template/view compile time
2. that [`CHANGELOG.md` file][2] is woefully out of date for a reason that escapes me

This is something related to #110 where I had to rethink pretty much everything to keep translations in sync with a specific English base version. We may have to be sneaky and move a version of the `CHANGELOG.md` file with the top release/version set to each version (0.3.0, 1.0.0, 1.1.0) as the topmost `CHANGELOG.md` release in the `en/` translation folder and then update all the `File.read` calls in every version translation to the appropriate subfolder copy of `CHANGELOG.md`.

It's not very hard but a bit tedious. If my breakdown was clear enough, do you want to help @coproc? 😃 

[1]: https://github.com/olivierlacan/keep-a-changelog/blob/5bc1cc0c63b27e58a51727f691761c1e6ee0990b/source/en/1.1.0/index.html.haml#L29
[2]: https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

**Comment by coproc** [comment]
Although I would like to help, I have to say currently 'no' because more pressing issues are waiting ...

**Comment by shoulders** [comment]
can i bump this issue. It might seem a small issue but it is fact a big one. I am using this as a standard but everytime i check https://keepachangelog.com/ it shows the old version (it has done for a while)

I would like it so when i visit https://keepachangelog.com/ I always get the latest standard.

It might seem lazy not to check github but when you are are just starting out programming every little extra things seems enormous.

Keep up the good work + I know most coding jobs take more that 5 mins :)

**Comment by varac** [comment]
Please update the website to show the latest released version by default.

**Comment by olivierlacan** [comment]
Should be addressed by [3c38a59](https://github.com/olivierlacan/keep-a-changelog/commit/3c38a59bceb390f0ed60dd6757c724f56b94a810) at least partially.

The trick is that I don't think the website will ever track patch releases because that would make tracking translations even more complicated. 

Currently I don't need any translations to be updated when we release a minor version because that will *never* include any language changes (other than typo fixes that don't impact translations). Any significant change to the Keep a Changelog guidelines will elicit a minor or a major version release.

Those new minor or major versions would then need to trickle down to each of (26 so far) international translations. That's a lot of work.
