### ISSUE TITLE
What about upgrading notes

### ISSUE THREAD

**Issue by MattKetmo** [olivierlacan/keep-a-changelog#34]
Something more useful than a change log is a note about "how to upgrade to the next version".

Let's take for instance the [symfony/symfony](https://github.com/symfony/symfony) repo. There are some [CHANGELOG files](https://github.com/symfony/symfony/blob/master/CHANGELOG-2.5.md) (which are just a log of git commits, so yes, quite useless), but it also provides [UPGRADE files](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md) to better explain to the end user the impacts on his project. It's not listing all the important changes between versions but focuses on the actions the user must do (updating his code if the project is a lib or, for instance, upgrading a database if the project is a full application).

My question is: should we include those "upgrading notes" into the change log or keep them apart?
IMO as it could be quite long it's better to have a separate file, but for quick actions it could make sense to have a dedicated sub section. What do you think?

**Comment by lunemec** [comment]
Agree with @nbibler. Separate UPGRADE file from CHANGELOG, being able to link from CHANGELOG to UPGRADE file.

Maybe we can look at UPGRADE file as well (unless some other project already does that).

**Comment by bucaran** [comment]
@MattKetmo What about `NOTES.md` with your "release notes" for all the miscelanea you want to inform users and developers alike. Also, there is [NEWS](https://www.gnu.org/prep/standards/html_node/NEWS-File.html#NEWS-File), which is like the CHANGELOG, but for "users" as opposed to developers.

**Comment by mbrand12** [comment]
Excellent idea. 

With every new major version it would be a good idea to add a reminder (a note) to check the `UPDATE.md` for information on how to transfer between major versions.

I think that the `NEWS` mentioned by @bucaran are more like what `CHANGELOG` is right now, since for me a "user" is anybody who uses the public API of my project, and they might very well be developers, and everything that is crucial to the actual end user should be outlined in the changelog in either Deprecated or Removed sections.

**Comment by bucaran** [comment]
@mbrand12 I agree and I prefer the simplicity of having only a CHANGELOG. Having a separated NEWS and CHANGELOG only applies to projects where "user" != "developer".

**Comment by cryode** [comment]
I believe that, rather than asking if we should add a very specific standard regarding upgrade notes, we should ask if there's a way we can provide a standard mechanism for user-defined sections / content.

Needs for upgrade or otherwise related-but-not-exactly-changelog notes will vary depending on project and/or team. An open source framework might require an upgrade guide in addition to a change log, whereas a single project internal team might prefer to consolidate documentation into one place.

Perhaps we should come up with a way to allow user-defined sections ("upgrade notes" or whatever!), and ensure the standard accepts such additions, allowing for parsers/interpreters to take advantage of them in whatever way the project deems necessary.
