### ISSUE TITLE
[Request] Add a tools section

### ISSUE THREAD

**Issue by xurei** [olivierlacan/keep-a-changelog#374]
I recently discovered this methodology and I think it's great ! 
I would like to use it in my projects, but I missed a "Tools" section in the website.

I found this repo: https://github.com/nicwest/kacl. 
It fits my needs, but I guess there are other tools out there.

**Comment by olivierlacan** [comment]
Hi, I've repeatedly declined recommendations and suggestions for tools in Keep A Changelog because I can't vouch for the tools in any meaningful way. This is a project to provide guidelines oriented towards humans, not tools or machine-ingestion of changelogs.

I'm sure people can find processes if they want to come up with processes to create their changelogs. My recommendation is to use whatever works for you, but remember that no tool will make your changelog human-oriented.

**Comment by xurei** [comment]
While I understand your intentions not to vouch for tools, I believe you misunderstand what kind of tools I'm referring to.

Let me give you a concrete example :
I work on a mobile app following the Keep A Changelog methodology. It's written and maintained by humans (i.e. myself), as you recommend.
However, there are other channels where the changes should be shown. In that case, the Play Store and App Store "What' new?" sections.
To achieve this, I have two options:
copy/paste the changes in the changelog at each release (which is prone to human error),
OR
use some tooling in our CI to automate this process.

A CI can also automate the "release" process (i.e. change the [Unreleased] section with the new version number generated by the CI, commit it, etc).


I believe this use case fit with the "Written by humans, for humans" ideology. That being said, I understand that you don't want to promote tooling here. 

Let me suggest a compromise: how about some blog articles *you* find useful and would help newcomers to understand what is possible with Keep A Changelog ?
