### ISSUE TITLE
Links to groups of changes are not stable and potentially confusing, demote them?

### ISSUE THREAD

**Issue by eugenesvk** [olivierlacan/keep-a-changelog#388]
One of the principles mentioned on [your site](https://keepachangelog.com/en/0.3.0/) is
> Easy to link to any section (hence Markdown over plain text).

...and that's a good thing! However, when it comes to __groups of changes__ for each version (e.g. Added/Changed/Removed) linking might be confusing since these links are not permanent and change with versions due to the fact that the group names are not unique and are differentiated by ordinal postfixes

For example, links to versions are permanently uniquely identified by the title itself (version+date): 
- `...CHANGELOG.md#110---2019-02-15` links to version [1.1.0](https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md#110---2019-02-15)
- `...CHANGELOG.md#100---2017-06-20` links to version [1.0.0](https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md#100---2017-06-20)

But similar links to the __Added__ section in temporary uniquely identified with ordinal postfixes `-1`, `-2` etc.
- `...CHANGELOG.md#added-1` links to group [Added@1.1.0](https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md#added-1)
- `...CHANGELOG.md#added-2` links to group [Added@1.0.0](https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md#added-2)

..and these postfixes change on updates, so e.g. when a new version __2.0.0__ is added and it also has the group __Added__, then the `...CHANGELOG.md#added-1` will stop referring to the __v1.1.0__'s section as is does now and refer instead to the __v2.0.0__'s
This __decreases the utility__ of sticking to the aforementioned principle of easy links

# Suggestion:
Maybe just demote each of the group under each version to bullet points like so:

## [1.1.0] - 2019-02-15

  - __Added__
    + Changelog inconsistency section in Bad Practices

## [1.0.0] - 2017-06-20

  - __Added__
    + Version navigation.

**Comment by FRodrigues-BrandenPT** [comment]
I liked your remark, but instead of using a bullet point, in my project, I simply add the version to the group like this:

# Changelog
## [1.0.0-RC1](#100-rc1---2021-04-02) - 2021-04-02
### Added `1.0.0-RC1`
 - Configuration

**Comment by olivierlacan** [comment]
This is indeed not great, but I really don't think it's a grave issue. At the very least most Markdown renderers will consistently render the version release header as a unique anchor. 

Not having sub-sections stay canonical when new releases are added is a bummer, but it's something that could be fixed by the Markdown renderer without requiring unnecessary duplication of version numbers. 

> Maybe just demote each of the group under each version to bullet points like so:

That means we lose linkable *and* TOC generation for Markdown renderers that offer this feature, not worth it in my book.

Unless someone can come up with a more elegant and non-duplicative solution, this is a won't-fix for me.

**Comment by Rabadash8820** [comment]
Sorry to necro this Issue, but it's the only one with discussion about making changelog links unique _and_ permanent, so I thought I'd add this for future Googlers:

The best way to handle this would probably be something like [heading IDs](https://www.markdownguide.org/extended-syntax/#heading-ids). You could then write your changelogs like so:

```md
## 2.0.0
### Added {#2.0.0-added}
### Changed {#2.0.0-changed}

## 1.0.0
### Added {#1.0.0-added}
### Changed {#1.0.0-changed}
```

and the renderer would auto-generate unique/permanent heading anchors. This _would_ duplicate version numbers in the heading IDs, but at least the duplication is only apparent to the authors and not cluttering the rendered document itself. This is probably the best that we could ever expect from a renderer, since they don't understand the semantics of a changelog and must rely on the author to make permanent anchors. 

Unfortunately, GitHub does not support heading IDs yet, as of this writing in 2025. 😔 GitHub _does_ support [custom anchors](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#custom-anchors), allowing you to write a changelog like so:

```md
## 2.0.0
### <a name="2.0.0-added"></a> Added
### <a name="2.0.0-changed"></a> Changed

## 1.0.0
### <a name="1.0.0-added"></a> Added
### <a name="1.0.0-changed"></a> Changed
```

Unfortunately, in addition to duplicating version numbers again, these custom anchors are not used by the little "anchor button" next to the headings in the rendered Markdown. Clicking those buttons will still put an auto-generated anchor like `#added-1` in the address bar. These custom anchors are only useful for referencing from elsewhere in the document.

Manually defining headings in HTML does not work either:

```md
## 2.0.0
<h3 id="2.0.0-added">Added</h3>
<h3 id="2.0.0-changed">Changed</h3>

## 1.0.0
<h3 name="1.0.0-added">Added</h3>
<h3 name="1.0.0-changed">Changed</h3>
```

GitHub seems to completely ignore the provided `id`s/`name`s and still uses the auto-generated anchors in the rendered anchor buttons next to the heading. 

So, as far as I can tell, the best we can really do to make our heading anchors unique is to make the headings something like `Added in 1.0.0`, as [suggested](https://github.com/olivierlacan/keep-a-changelog/issues/388#issuecomment-812588057) by @FRodrigues-BrandenPT above.
