### ISSUE TITLE
Nu Html Checker: Improve Html Quality

### ISSUE THREAD

**Issue by throwaway-d** [olivierlacan/keep-a-changelog#453]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fkeepachangelog.com%2F
![image](https://user-images.githubusercontent.com/121148372/219942237-154ecb99-2879-43cf-9c3e-586afc7790f5.png)
- About `lang` attribute: https://dequeuniversity.com/rules/axe/4.4/html-has-lang
- About trailing slashes: https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements

**Comment by olivierlacan** [comment]
The W3 tools doesn't follow redirects, so virtually none of this is useful: 


```curl keepachangelog.com
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

You have to feed it final URLs from resolved 301s:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fkeepachangelog.com%2Fen%2F1.1.0%2F
 
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/65950/223611920-1e5e0987-7703-47f3-9555-95d2249bf854.png">

99% of the errors shown pertain to `aria_hidden` being used on anchor tags for headers, which we do indeed *not* want to put in the document accessibility tree since they'd be a huge pain for assistive devices.

**Comment by throwaway-d** [comment]
What about this though?
![image](https://user-images.githubusercontent.com/121148372/223612921-70ff1baf-f76c-4608-bf1f-d341bf6cf93e.png)

**Comment by olivierlacan** [comment]
Fixed the warnings, trailing slash issue is a wont fix since this is Haml-generated and not a concern. Won't fix that.

Thanks.

**Comment by throwaway-d** [comment]
Thank you for fixing them. I also have found some other things:
![image](https://user-images.githubusercontent.com/121148372/224033567-2a1733e8-81e3-46ba-89fb-1e9319138380.png)
![image](https://user-images.githubusercontent.com/121148372/224033643-69e97010-efc9-46ab-8fd8-27dda599cd57.png)
