### ISSUE TITLE
use GitHub labels or split off to separate repo to differentiate between issues

### ISSUE THREAD

**Issue by axd1967** [olivierlacan/keep-a-changelog#460]
A lot of issues have been popping up that are related to the website, while IMHO this GitHub repo is mainly about discussing core Changelog issues - but I might be mistaken, please forgive me if that would be the case.

Would it be possible to split off pure (conceptual) Changelog issues from anything not related to the website?

The reason is that I'm not interested in technical issues of https://keepachangelog.com/ but I'm flooded with such issues, and have difficulties in weeding out the real changelog issues.

Consider creating a separate GitHub repo for the technical issues, and keep this repo for the conceptual issues; GitHub makes it very easy to move issues to other repos.

**Comment by olivierlacan** [comment]
I'd rather we turn the conversations about Keep a Changelog into GitHub Discussions actually, since many had nothing to do with actual fixable issues. 

I'll be converting old issues that were in fact conversations in Discussions. Notably to allow folks to up/downvote and to surface the most pressing questions folks want to discuss.

But thanks from bringing this idea, it's a good one. 😃

**Comment by axd1967** [comment]
Anyone that needs to limit the emails to conceptual issues, go here:

![image](https://user-images.githubusercontent.com/3529789/231662224-9a219aad-2956-4d41-8e5e-440042ee8729.png)
