### ISSUE TITLE
Link to the "standard" Perl format somewhere?

### ISSUE THREAD

**Issue by autarch** [olivierlacan/keep-a-changelog#49]
There's already a standard that is at least somewhat widely used in the Perl community. See https://metacpan.org/pod/CPAN::Changes::Spec for details. It's a bit looser than what you propose, but the ideas are very similar. There's also a [testing module](https://metacpan.org/pod/Test::CPAN::Changes) people can use to verify that their `Changes` file follows the spec.

**Comment by lunemec** [comment]
IMO the markdown syntax is a great idea, because most people already use it for their readme and other documentation, so it makes sense to use it as well, not the perl standard ....

The tool is very good idea, it should be part of this package... If I may suggest Python or Go as a language for this tool :)

**Comment by autarch** [comment]
I wasn't suggesting linking to the Perl standard as a suggestion for other languages. But if you're doing something with Perl, it makes a lot more sense to stick with an existing standard than to introduce a new one.

**Comment by lunemec** [comment]
@autarch agreed

**Comment by davidak** [comment]
Could also be linked in our README as similar project.

**Comment by olivierlacan** [comment]
I don't think release notes should be language specific. Users should be able to find consistent changelogs and release notes across languages. Interoperability and all.

All here for taking inspiration when needed however.
