### ISSUE TITLE
Seemingly GitHub links are broken

### ISSUE THREAD

**Issue by slim71** [olivierlacan/keep-a-changelog#568]
Throughout the page there are a couple of links which seem they should point to this repo, but they do not.
![image](https://github.com/olivierlacan/keep-a-changelog/assets/39267642/3ee120bd-747d-4c2f-a4f9-5a142d155869)
![image](https://github.com/olivierlacan/keep-a-changelog/assets/39267642/7fd3a118-d9c1-447e-8aec-b95612773526)
![image](https://github.com/olivierlacan/keep-a-changelog/assets/39267642/6054f942-1cf5-4610-a659-73c62074825b)

**Comment by edmorley** [comment]
I encountered this too.

**Comment by Patrickode** [comment]
I think this is because the links in [index.html.haml](https://github.com/olivierlacan/keep-a-changelog/blob/823f4ce1e02ad4b40625c31f46895e28b03d967e/source/en/1.1.0/index.html.haml#L185C35-L185C51) point to the link called "issue," which does not exist; the proper title is "issues," plural (see data/links.json).

I've made a pull request to do that here: #575

**Comment by olivierlacan** [comment]
It's been fixed, thanks y'all! 😃
