### ISSUE TITLE
Opening homepage in FF 40 causes prompt for file download

### ISSUE THREAD

**Issue by Relequestual** [olivierlacan/keep-a-changelog#76]
Loading the site root in firefox version 40 causes a prompt for CHANGELOG.md to be downloaded. It doesn't do this in chrome, so I don't know if it is a firefox bug or a problem with the code here. in firefox it doesn't display the changelog for the site, where as in chrome it does.

**Comment by PikachuEXE** [comment]
I have the same problem too. But I am using `38.2.1` (ESR)
iframe processing logic changed?

**Comment by olivierlacan** [comment]
Still an issue?

**Comment by mbrand12** [comment]
Yes. It still prompts for a download.

**Comment by nbibler** [comment]
Confirmed in FF 40.0.3 and 41.0.1, OS X 10.11.

**Comment by nbibler** [comment]
Seems to be an issue with Firefox not wanting to parse non-HTML files, according to [this non-authoritative post](http://stackoverflow.com/questions/30860875/why-txt-file-in-iframe-is-getting-downloaded-instead-of-displayed).

**Comment by nbibler** [comment]
I wonder if rather than using the current IFRAME approach, we instead add jQuery and an empty PRE to the index.html. With that, I imagine we could `$("pre").load("/CHANGELOG.md");` and avoid having Firefox do _any_ content negotiation at all.

I think it's functionally pretty similar to what's going on right now with the IFRAME. It'd still be two network requests to fully load the page...

It's a little crazy and someone later on would wonder why the heck *that* was done. ;)

**Comment by olivierlacan** [comment]
Sounds good to me. Trying it out.

**Comment by nbibler** [comment]
Following #79, this appears to no longer be a problem. Please reopen if so!
