### ISSUE TITLE
Who is this project for?

### ISSUE THREAD

**Issue by lambda** [olivierlacan/keep-a-changelog#83]
One of the things I am left wondering when reading the spec and some of the issues in this project is the question of what audience this project is intending to target; in fact, what two audiences.

The first is what types of projects. There are a few different major types of software projects. One is libraries, that are intended to be used by other developers, or possibly hosted APIs. Another is server software being delivered to sysadmins, or maybe anything highly technical; the end users are expected to be technically proficient and know a bit about how the software works, but are not necessarily API consumers. The last is end-user facing software; hosted software intended intended for non-technical end users, or desktop or mobile software intended for them.

The other question is who the audience for the changelog is, which is a slightly different question than above. While the audience could be the primary users of the software, it could also be downstream distributors such as package maintainers for software that gets packaged in Linux or BSD distros, or it could be other developers, QA, and tech support within the project itself.

The answers to these questions would influence some of the other open discussions I see on this repo. For instance, issue #2 about which changes should be included. If it's intended for team members who are heavily involved in the project itself, it should probably include all changes like a GNU style ChangeLog, though I think that with modern Git commit message conventions that's redundant, the Git log is where people involved in the project itself should be looking.

Issue #30 is also related to this. It mentions marking internal vs. external changes. Perhaps the idea here is that the changelog is for the internal team, but a user-facing release notes should be extractable from it?

The other audience that isn't frequently thought of, besides internal people and external users, is external packagers. Things like reorganizations of data files or splitting up of single binaries into libraries and multiple binaries, licensing audits, and the like may be important to them.

What type of software this is targeting is also important. For developer-facing APIs, pretty much every change that affects the external API should be documented, as well as any major internal changes that may affect its behavior. For sysadmin oriented software, any data migrations that might be necessary should be mentioned. For end user oriented software, probably only user visible changes and added removed functionality should be mentioned.

However, sometimes a single project is more than one of these things. You may have a hosted service, that has both a programmatic API and an end-user facing interface.

Defining which of these types of projects, and which of these types of users, is in scope for this document would be good. If they are all intended to be in-scope, then there may need to be a decision on how to support all of them if they have conflicting requirements, for instance some changes that are internal only, or some that affect the API while some that affect the UI.

Is the goal to support those through multiple different changelogs, or some master changelog from which each could be extracted?

**Comment by mbrand12** [comment]
Currently I see this project more as a set of practical guides to make the changelog more understandable and accessible to whomever the audience is, what they actually put in sections and to which level of detail they go is up to them.

Weather you have two or more different changelogs, the basic idea for me is to follow the guidelines when it comes to putting dates, putting compare links (if the repo is on github), sectioning your changes to "added", "removed" etc.

Also how you have generated that change log (meaning that if you have a master changelog that is filtered/rendered differently depending who is accessing it) is also up to you.

Here is an example:

While [this](https://github.com/k0kubun/hamlit/blob/ed541eb4c8d62e7dab46c1e5ab050537473b32dd/CHANGELOG.md) chagelog is comprehensive however when [formatted](https://github.com/k0kubun/hamlit/blob/d927931578066d63c04fb7e87e1f987ad5358270/CHANGELOG.md) following this project guidelines it contains much more information while not really changing the content.

Also one of the good side effects of using these guidelines is that when identifying what change belongs in what section it also helps when determining the release version number.

This project, in my opinion should be used like semantic versioning is used. With semantic versioning you don't care what is in the project you only care that a major version number will change when either something is removed and it will cause something to break or some new feature worthy of a major number change. And here is whnere this project comes in for me, when I want to quickly see what is the breaking change instead of reading the whole changelog changes list for that version I just jump to the subheading "Changes" and see if there are any [**breaking**] tags.

And once this or any other format for changelog has became a more wide used standard imagine if for example you can set bundle to display only breaking changes on gem install or anything like this. The reason why this would be possible is because of the standardised way of writing changelogs.

With GitHub for example, thanks to the compare links, the commit messages actually complement the changelog since you can view the full commit message and implementation details.

Though while I agree that filtering a master changelog is not a bad idea, using commit messages for changelog messages is a bad idea (as noted in the readme of this project), since people use far to many different commit styles.

So the goal, in my opinion, of this project is just to make those changelogs more readable by motivating everybody to use the same or at least similar format, while how you filter you changelog for a different audience, or weather you maintain more than one in the same project  is mostly up to you.

I hope I haven't missed the point of your question by allot :)

**Comment by olivierlacan** [comment]
This project is for software developers.

**Comment by olivierlacan** [comment]
I really don't mean to dismiss this question. I'll read both of your posts a bit later but I wanted to answer the question as soon as possible.

**Comment by lambda** [comment]
That answer is a little too short to answer my question; and actually, I'm left wondering which question you answered, because just reading the title my question could be interpreted ambiguously, and you indicate that you haven't read the full post.

I'm not asking about who this specification is intended for; it's obviously intended for software developers writing a change log of their software. I'm curious about who the intended audience of the change logs that it describes is; is that audience intended to be other software developers on the same project, other software developers using an API provided by the project, technical users, downstream packagers, or non-technical end users. More than one may be in scope, or perhaps the intent is to provide a specification for change logs that contain all of the information in a way that could be trimmed down for different audiences (as some of the discussion about marking certain changes `INTERNAL` in order to filter them out for release notes).

I'm asking this question because I had some other issues to bring up for clarification or patches to send, but some of them only make sense depending on the intended audience of the change logs. I'm trying to figure out what is in scope for this project.
